---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04

suites:
  - name: default
    run_list:
      - recipe[apt]
      - recipe[build-essential]
      - recipe[drupal::init]
      - recipe[sudo]
      - recipe[git]
      - recipe[mysql::server]
      - recipe[drupal::ssh]
      - recipe[drupal::apache]
      - recipe[drupal::php]
      - recipe[drupal::drush]
      - recipe[drupal::mysql]
      - recipe[drupal]
    data_bags_path: test/integration/data_bags
    data_path: test/integration/data
    attributes:
      build_essential:
        compiletime: true
      mysql:
        server_root_password: root
        server_repl_password: root
        server_debian_password: root
      db:
        driver: "mysql"
        client_recipe: "mysql::client"
        root: "root"
        grant_hosts: ["localhost"]
        users:
          root: "root"
          replication: "replication"
          debian: "debian"
      php:
        directives:
          memory_limit: "1024M"
          upload_max_filesize: "200M"
          post_max_size: "210M"
        conf_dir: "/etc/php5/apache2"
      drupal:
        server:
          web_user: "www-data"
          web_group: "www-data"
          assets: "/assets"
          base: "/srv/www"
        sites:
          example:
            active: true
            deploy:
              action:
                - deploy
                - install
              releases: 1
            drupal:
              version: "7.26"
              install:
                install_configure_form.update_status_module: "'array(FALSE,FALSE)'"
                "--clean-url": 1
              settings:
                profile: "standard"
                files: "sites/default/files"
                cookbook: "drupal"
                settings:
                  default:
                    location: "sites/default/settings.php"
                  example_template:
                    location: "sites/default/example.settings.php"
                    template: "example.settings.php.erb"
                  example_static:
                    location: "profiles/standard/standard.settings.php"
                db_name: "example"
                db_host: "localhost"
                db_prefix: ""
                db_driver: "mysql"
                db_file: ""
            repository:
              host: "github.com"
              uri: "https://github.com/drupal/drupal.git"
              revision: "7.26"
            web_app:
              "80":
                server_name: "drupal.local"
                rewrite_engine: "On"
                docroot: "/srv/www/example/current"
