language: ruby

rvm:
  - 1.9.3
  - 2.0.0

install: 
  - bundle install
  - sudo wget -nv http://files.vagrantup.com/packages/7e400d00a3c5a0fdf2809c8b5001a035415a607b/vagrant_1.2.2_x86_64.deb
  - sudo dpkg -i vagrant_1.2.2_x86_64.deb

script: bundle exec rake test
